### ISSUE TITLE
Add type implementation

### ISSUE THREAD

**Issue by CohenArthur** [CohenArthur/jinko#85]
- [x] Add type design #79 
- [x] Add type parsing #80 
- [x] Implement types in the interpreter #138
